version: "3.8"
services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5001

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    build: .
    environment:
      - FLASK_ENV=testing
      - FLASK_APP=app
    volumes:
      - .:/app
    command: pytest --maxfail=1 --disable-warnings -v
    depends_on:
      - db
    profiles:
      - test

volumes:
  postgres_data:
