"""Initial migration

Revision ID: 0de40db6210a
Revises: 4260b7fa759b
Create Date: 2024-12-21 18:12:22.714209

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0de40db6210a"
down_revision = "4260b7fa759b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.alter_column("answer_text", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.alter_column("answer_text", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###
